dist: noble
sudo: required

before_install:
  - sudo apt update
  - sudo apt install apt
  - sudo apt-get install php8.4

before_script: composer install

script:
  - vendor/bin/phpunit tests

notifications:
  slack: dragonflyrg:w3hYXjTOZjrmBGQuszMILN7K#opensource_notify
