dist: oracular
sudo: required
language: php
php: 8.4

before_script: composer install

script:
  - vendor/bin/phpunit tests

notifications:
  slack: dragonflyrg:w3hYXjTOZjrmBGQuszMILN7K#opensource_notify
