name: CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.4' # Adjust as needed

    - name: Install PHP Sockets Extension
      run: |
        sudo apt-get update
        sudo apt-get install -y php8.4-sockets

    - name: Check Installed PHP Extensions
      run: php -m | grep sockets  # Debugging step to verify installation

    - uses: php-actions/composer@v6 # or alternative dependency management
    - uses: php-actions/phpunit@v3
      with:
        version: 9.6
        bootstrap: vendor/autoload.php
        args: tests
