name: CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest
    container:
      image: php:8.4  # This forces the job to run in a Docker container

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install and Enable ext-sockets
      run: |
        docker-php-ext-install sockets
        docker-php-ext-enable sockets

    - uses: php-actions/composer@v6 # or alternative dependency management
    - uses: php-actions/phpunit@v3
      with:
        version: 9.6
        bootstrap: vendor/autoload.php
        args: tests
